# -*- coding: utf-8 -*-
"""week3-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14J30QFBkpfKLg-K9bYu_vT0FGQoOH6tw
"""

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset("flights")
data = data.pivot("month", "year", "passengers")

# Heatmap
sns.heatmap(data=data, annot=True, fmt="d", cmap="YlGnBu")
plt.show()

data.info

data = sns.load_dataset("flights")
sns.lineplot(data=data, x="year", y="passengers")
plt.show()

data = sns.load_dataset("iris")
sns.swarmplot(x="species", y="petal_length", data=data)
plt.show()

data = sns.load_dataset("titanic")
sns.countplot(data=data, x="class")
plt.show()

data = sns.load_dataset("tips")
sns.scatterplot(data=data, x="total_bill", y="tip")
plt.show()

data = sns.load_dataset("titanic")
g = sns.FacetGrid(data, col="sex")
g.map(sns.histplot, "age")
plt.show()

iris = sns.load_dataset("iris")
g = sns.clustermap(iris.drop("species", axis=1), cmap="coolwarm", standard_scale=1)
plt.show()

iris.info

